# Generated by Django 5.0.6 on 2024-06-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="media/"
            ),
        ),
    ]
